{{- if .Values.trivy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "harbor.trivy" . }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
  redis: {{ include "harbor.redisForTrivyAdapter" . | b64enc }}
{{- end }}
